Wish_List/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace = "users")),
    url(r'^', include('apps.dashboard.urls', namespace = "items")),
]

apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard', views.success, name="success"),


    url(r'^wish_items/create', views.create, name="create"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^home$', views.home, name = "home"),
    url(r'^create_item$', views.adding_item, name = "item"),
    url(r'^wish_items/item_detail/(?P<id>\d+)$', views.item_detail, name = "item_detail"),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = "delete"),
    url(r'^move_up/(?P<id>\d+)$', views.move_up, name = "move_up"),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = "remove"),
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..user_app.models import User




class ItemManager(models.Manager):
    def add_item(self, item, userID):
        response={}
        errors=[]
        if Item.objects.filter(item_name = item):
            #item = request.post['item']: name we gave in html
            errors.append("Sorry that item exists")
        if len(item) < 3:
            errors.append("Invalid Item! Item should not be less than 3 characters")
        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status']=True
            response['items'] = Item.objects.create(item_name=item, created_by=User.objects.get(id = userID))
            response['items'].wished_by.add(User.objects.get(id = userID))
        return response

    def item_detail(self, UserID):
        return self.get(id = UserID)

    def delete (self, id):
        self.get(id = id).delete()





class Item(models.Model):
    item_name= models.CharField(max_length =225)
    created_by= models.ForeignKey(User, related_name="created")
    wished_by=models.ManyToManyField(User, related_name="wished")
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects = ItemManager()

apps/dashboard/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Item
from ..user_app.models import User
from django.contrib import messages


def success(request):
    if not 'id' in request.session:
        messages.add_message(request, messages.ERROR, "Please login.")
        return redirect('/')
    context = {
        'items': Item.objects.filter(wished_by = User.objects.get(id = request.session['id'])),
        'items_wished':Item.objects.exclude(wished_by = User.objects.get(id = request.session['id']))
    }

    return render(request, 'dashboard/index.html', context)

def adding_item(request):
    if request.method == "POST":
        print request.POST['item']
        userID = request.session['id']
        response = Item.objects.add_item(request.POST['item'], userID)

        if response['status'] ==False:
            for error in response['errors']:
                messages.add_message(request, messages.ERROR, error)
            return redirect("items:create")
        else:
            print "YAYYYYYY"
            messages.add_message(request, messages.SUCCESS, "You have successfully added item(s) to your wish list" )
            return redirect("items:success")

    else:
        messages.add_message(request, messages.ERROR, "login/register first")
        return redirect("/")


def create(request):
    if not 'id' in request.session:
        messages.add_message(request, messages.ERROR, "Please login.")
        return redirect('/')
    return render(request, 'dashboard/add.html')


def logout(request):
    request.session.clear()
    messages.add_message(request, messages.SUCCESS, "You have logged out!" )
    return redirect("/")


def home(request):
    return redirect("/dashboard")

def item_detail(request, id):
    response = Item.objects.item_detail(id)
    context= {
        'item_detail':response
        }
    return render(request, 'dashboard/each_item.html', context)

def delete (request, id):
    Item.objects.delete(id)
    return redirect('/dashboard')
    #  Item.objects.get(id = id).delete

def move_up(request, id):
    up = Item.objects.get(id = id)
    person = User.objects.get(id = request.session['id'])
    up.wished_by.add(person)
    return redirect('/dashboard')


def remove(request, id):
    rem = Item.objects.get(id = id)
    person = User.objects.get(id = request.session['id'])
    rem.wished_by.remove(person)
    messages.add_message(request, messages.SUCCESS, "You have successfully removed the item from your wishlist " )
    return redirect('/dashboard')

apps/dashboard/templates/dashboard/add.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Create Item</title>
</head>
<body>
<a href="{%url 'items:home' %}">Home</a>
<a href="{%url 'items:logout' %}">Logout</a>
<h1>Create a New Wish List Item</h1>
<form action="/create_item" method="POST">
{% csrf_token %}
Item/Product: <input type="text" name="item">
<input type="submit" name="Add" value = "Add">
</form>

{% if messages %}
{% for message in messages %}
  {{ message }}
{% endfor %}
{% endif %}


</body>
</html>

apps/dashboard/templates/dashboard/each_item.html
<!DOCTYPE html>
<html>
<head>
	<title>{{item_detail.item_name}}</title>
</head>
<body>

	<a href="{%url 'items:home' %}">Home</a><br>
	<a href="{%url 'items:logout' %}">Logout</a>
<h2>{{item_detail.item_name}}</h2>

	<p>Users who added this product/item under their wish list:</p>
  {% for item in item_detail.wished_by.all %}
  <ul>
  <li>{{ item.name }}</li>
</ul>
  {% endfor %}

</body>
</html>

apps/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>My Wish List</title>
	<meta charset="utf-8">
	{% load staticfiles %}
      <!-- The line above tells Django to be ready to listen for static files -->
      <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}" media="screen" title="no title"  charset="utf-8">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	</head>


	<body>
	<div id="container">
	<h2>Hello {{request.session.name}} !</h2>
	<a href="{%url 'items:logout' %}">Logout</a><br>

	<ul>
	{% if messages %}
	{% for message in messages %}

	<li>{{ message }}</li>
	{% endfor %}
	{% endif %}
	</ul>

	Your Wish List:<br>

	<table class="table table-bordered">
		<thead>
		<tr>
			<th>Item</th>
			<th>Added by</th>
			<th>Date Added</th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>

		{% for item in items %}
		<tr>
			<td><a href="{%url 'items:item_detail' item.id %}">{{ item.item_name}}</a></td>
			<td>{{item.created_by.name}}</td>
			<td>{{item.created_at.date}}</td>
			{% if item.created_by.id == request.session.id %}
			<td><a href="{%url 'items:delete' item.id  %}">Delete</a></td>
			{% else %}
			<td><a href="{%url 'items:remove' item.id  %}">Remove from my wishlist</a></td>
		</tr>

		{% endif %}
		{% endfor %}

		</tbody>
	</table><br>

	<a href="{%url 'items:create' %}">Add Item</a><br><br>

	Other User's Wish List:<br>
	<table class="table table-bordered">
		<thead>
		<tr>
			<th>Item</th>
			<th>Added by</th>
			<th>Date Added</th>
		<th>Actions</th>
		</tr>
		</thead>
		<tbody>
		{% for item in items_wished %}
		{% if item.created_by.id != request.session.id %}
		<tr>
			<td><a href="{%url 'items:item_detail' item.id %}">{{ item.item_name}}</a></td>
			<td>{{item.created_by.name}}</td>
			<td>{{item.created_at.date}}</td>
			<td><a href="{%url 'items:move_up' item.id  %}">Add to my Wishlist</a></td>
		</tr>
		{% endif %}
		{% endfor %}
		</tbody><br>
	</table>

	</div>
	</body>
</html>